src/Entity/InfoClient.php
<?php

namespace App\Entity;

use App\Repository\InfoClientRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InfoClientRepository::class)
 * @UniqueEntity(fields={"Mail"}, message="There is already an account with this email")
 * @UniqueEntity(fields={"nom_Societe"}, message="La société est deja enregister")
 */
class InfoClient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_Societe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Num_pro;

    /**
     * @ORM\Column(type="integer")
     */
    private $Cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Ville;

    /**
     * @ORM\Column(type="string")
     */
    private $num_siret;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_adm;

    /**
     * @ORM\Column(type="integer")
     */
    private $count_file;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getNomSociete(): ?string
    {
        return $this->nom_Societe;
    }

    public function setNomSociete(string $nom_Societe): self
    {
        $this->nom_Societe = $nom_Societe;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getNumPro(): ?string
    {
        return $this->Num_pro;
    }

    public function setNumPro(string $Num_pro): self
    {
        $this->Num_pro = $Num_pro;

        return $this;
    }

    public function getCp(): ?int
    {
        return $this->Cp;
    }

    public function setCp(int $Cp): self
    {
        $this->Cp = $Cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getNumSiret(): ?string
    {
        return $this->num_siret;
    }

    public function setNumSiret(string $num_siret): self
    {
        $this->num_siret = $num_siret;

        return $this;
    }

    public function getIdAdm(): ?int
    {
        return $this->id_adm;
    }

    public function setIdAdm(int $id_adm): self
    {
        $this->id_adm = $id_adm;

        return $this;
    }
   

    public function getCountFile(): ?int
    {
        return $this->count_file;
    }

    public function setCountFile(int $count_file): self
    {
        $this->count_file = $count_file;

        return $this;
    }
    public function __toString():string 
    {
        
        return $this->getNom();
        return $this->getCountFile();
    }
    
   
}

templates/files/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<div class="alert alert-success" role="alert">
 Page Operationnel @Nathan!
</div>
<div class="container">
<form name="file" method="post" enctype="multipart/form-data">
 <div class="form-group">
    <label for="exampleFormControlSelect1">Client</label>
    <select class="form-control" id="exampleFormControlSelect1" name="file[id_client]">
    {% for client in clients %}
      <option value="{{client.id}}">{{client.Nom}} - {{client.NomSociete}}</option>
     {% endfor %} 
    </select>
  </div>
  <br>
   <div class="form-group">
    <label for="exampleFormControlSelect1">Fichier demander</label>
    <select class="form-control" name="file[id_demande]" id="exampleFormControlSelect1">
      {% for demande in demandes %}
      <option value="{{demande.id}}">{{demande.Nom}}</option>
     {% endfor %} 
    </select>
    <br>
    <div class="form-group">
    <label for="exampleFormControlFile1">Veuillez ajouter le fichier</label>
    <input type="file" class="form-control" name="file_name" id="exampleFormControlFile1">
  </div>
  </div>
  <br>
<button type="submite" class="btn btn-success">Success</button>
  </form>
  </div>
{% endblock%}

templates/files/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<div class="container">
    <form name="file" method="post"">
        <label for="exampleFormControlSelect1">Fichier demander</label>
         <select class="form-control" name="file[id_demande]" id="exampleFormControlSelect1">
           {% for demande in demandes %}
           <option value="{{demande.id}}">{{demande.Nom}}</option>
          {% endfor %} 
         </select>
           <label for="exampleFormControlSelect1">Fichier demander</label>
         <select class="form-control" name="file[id_cli]" id="exampleFormControlSelect1">
         <option value="">Choisit un client</option>
           {% for test in tests %}
           <option value="{{test.id}}">{{test.nom}}</option>
          {% endfor %} 
         </select>
         <br>
         <br>
         <button type="submite" class="btn btn-success">Filtrer</button>
         </form>
          <br>
       
</div>
{% endblock%}

templates/files/test.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}

{{clients}}

{% endblock%}

templates/files/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TuestconnecterController!{% endblock %}

{% block body %}

<div class="container">
<br>
  <form name="file" method="post"">
        <label for="exampleFormControlSelect1">Fichier demander</label>
         <select class="form-control" name="file[id_demande]" id="exampleFormControlSelect1">
           {% for demande in demandes %}
           <option value="{{demande.id}}">{{demande.Nom}}</option>
          {% endfor %} 
         </select>
         <br>
         <label for="exampleFormControlSelect1">Clients</label>
         <select class="form-control" name="file[id_cli]" id="exampleFormControlSelect1">
          <option value="">Chosit un client</option>
           {% for test in tests %}
           <option value="{{test.id}}">{{test.nom}}.{{test.prenom}}: {{test.NomSociete}}</option>
          {% endfor %} 
         </select>
         <br>
      <button type="submite" class="btn btn-outline-success">Filtrer</button>
     {% if is_granted('ROLE_ADMIN') %}
         <a href="/admin/files"><button type="button" class="btn btn-outline-danger">Remove filtre</button></a>
        {% else %}
           <a href="/colab/files"><button type="button" class="btn btn-outline-danger">Remove filtre</button></a>
           {% endif %}


         </form>
         <br>
<h2>Liste des Fichiers</h2>
<br>

<table class="table">
  <thead>
    <tr>
     <th scope="col">Client</th>
      <th scope="col">Nom</th>
      <th scope="col">Fichier Demande</th>
     

  
    </tr>
  </thead>
  <tbody>
   {% for client in clients %}
    <tr>
      <th>{{client.prenom}}</th>
      <th scope="row"><a href="/viewpdf/{{client.name_md5}}" target="_blank">{{client.nom_fichier}}</a></th>
      <th>{{client.nom}}</th>
      
     
    
    </tr>
    {% endfor %}
   
  </tbody>
</table>
</div>



{% endblock %}

templates/files/view_client.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello TuestconnecterController!{% endblock %}

{% block body %}

<div class="container">
<br>
<h2>Liste des Fichiers</h2>
<br>
   {% for client in clients %}
<button type="text" class="btn btn-outline-primary">Client: {{client.prenom}}-{{client.nom_societe}}</button>
 {% endfor %}
 <br>
<br>
<table class="table">
  <thead>
    <tr>
     <th scope="col">Fichier</th>
      <th scope="col">Categorie</th>
      <th scop="col">Edit</th>
     
     

  
    </tr>
  </thead>
  <tbody>
   {% for client in clients %}
    <tr>
     
      <th scope="row"><a href="/viewpdf/{{client.name_md5}}" target="_blank">{{client.nom_fichier}}</a></th>
      <th>{{client.nom}}</th>
      <th><a href="/delete_file/{{client.id}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
  <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
</svg></a></th>
      
     
    
    </tr>
    {% endfor %}
   
  </tbody>
</table>
</div>



{% endblock %}